# Generated by Django 2.2.5 on 2019-09-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_question_questionset'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='position',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
